export const FETCH_QUIZ = 'FETCH_QUIZ';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const RESET_QUIZ = 'RESET_QUIZ';
